import type { Metadata } from "next"
import Image from "next/image"
import { Inter } from "next/font/google"

import { clsx } from "clsx"

import "./styles.scss"
import { ThemeProvider } from "./_components/ThemeProvider"

const inter = Inter({ subsets: ["vietnamese"] })

export const metadata: Metadata = {
  title: "HackerRank Viewer",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx(
          inter.className,
          "flex flex-col",
          "min-h-screen",
          "bg-gray-50 dark:bg-stone-950",
        )}
      >
        {/* {children} */}
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
