import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { clsx } from "clsx"

import "./styles.scss"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "HackerRank Viewer",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, "flex flex-col", "min-h-screen")}>
        <header></header>

        <main className={clsx("flex-1")}>{children}</main>

        <footer></footer>
      </body>
    </html>
  )
}
